name: a

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  a-job:
    runs-on: ubuntu-latest

    steps:
      - name: a payload
        run: |
          sleep 5
          cat $GITHUB_EVENT_PATH
