name: collect statuses

on:
  workflow_run:
    workflows: ["a", "b", "c", "d"]
    types: 
      - completed

  workflow_dispatch:

jobs:
  collect-statuses:
    runs-on: ubuntu-latest

    steps:
      - name: payload
        run: |
          cat $GITHUB_EVENT_PATH
      - name: get job statuses
        run: |
          TRIGGERED_FROM=$(cat $GITHUB_EVENT_PATH | jq -r '.workflow_run .name')
          HEAD_SHA=$(cat $GITHUB_EVENT_PATH | jq -r '.workflow_run .head_sha')
          CHECK_RUNS=$(curl --silent -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/commits/${HEAD_SHA}/check-runs | jq ".check_runs | .[] | {job_name:.name,job_status:.status,job_conclusion:.conclusion}")
          echo "*****************"
          echo "Triggered from workflow: ${TRIGGERED_FROM}"
          echo "commit head sha: ${HEAD_SHA}"
          echo "check runs for commit: ${CHECK_RUNS}"

